name: Static checks
on:
  pull_request: {}
  push:
    branches:
    - main
permissions: 
  contents: read
jobs:
  markdown_lint:
    name: Markdown lint
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
    - name: Markdown lint
      run: bin/markdownlint-all
  chart_docs_diff:
    name: Chart readme diff check
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
    - name: Check docs for diff
      run: bin/helm-docs-diff
